### ISSUE TITLE
Board not working when Jumpers were not kept

### ISSUE THREAD

**Issue by selvakumaran2016** [bigtreetech/BIGTREETECH-OCTOPUS-V1.0#103]
Hi all,

We are using the Octopus V1.1 board. We have already used 2-3 boards and all are working properly.

In one board, while keeping the jumpers for the Motor 7 Stepper driver, we forget to keep any jumpers. (All other 6 motors are properly connected with Jumpers). Without any jumper, we inserted A4988.

A small burning smell came and the board became dead. 

The marked chip in the below image looks burnt. The main processor is not showing any signs of burning.

Please suggest whether we can change this? and what is that IC name?

Now when connecting to PC, it is not showing any port. And even no LED is glowing.

Thanks in advance

![BTT Octopus](https://user-images.githubusercontent.com/16957075/154226069-169f3c16-1a09-4045-a572-c325c1d170b5.jpg)

**Comment by radek8** [comment]
It should be a 3.3V VCC voltage regulator

![image](https://user-images.githubusercontent.com/46979052/154857384-c85cba8a-c0ac-4f03-a62a-75a37d93d0e3.png)

**Comment by radek8** [comment]
These should be two matched voltage regulators.

![image](https://user-images.githubusercontent.com/46979052/154857482-71a10a33-32b3-402e-b78c-299ab349e4ed.png)

**Comment by radek8** [comment]
RT9193-33GB

**Comment by radek8** [comment]
https://de.aliexpress.com/item/4000387137481.html?gatewayAdapt=glo2deu&af=3762815_1&cv=37665065&cn=45r7m8frcmtfz2dbql3r2t7bbcrgho48&dp=v5_45r7m8frcmtfz2dbql3r2t7bbcrgho48&utm_source=epn&utm_medium=cpa&utm_campaign=3762815_1&utm_content=37665065&product_id=4000387137481&afref=https%3A%2F%2Falipromo.com%2Fredirect%2Fcpa%2Fo%2Fq3uk36t2i4ehtdo7wys72lakq0y01lgl%2F&aff_fcid=1239808ea90941e28f5889b97f3c29f1-1645381431820-06490-_d6yGheF&aff_fsk=_d6yGheF&aff_platform=api&sk=_d6yGheF&aff_trace_key=1239808ea90941e28f5889b97f3c29f1-1645381431820-06490-_d6yGheF&terminal_id=290428c8106c48438ea1ffecefca338b

**Comment by selvakumaran2016** [comment]
@radek8 Great. Thanks for the support. Will order this...
