### ISSUE TITLE
Marlin\src\HAL\shared\HAL.cpp - MarlinHAL does not name a type - PlatformIO

### ISSUE THREAD

**Issue by NorbertRoller** [bigtreetech/BIGTREETECH-OCTOPUS-V1.0#111]
D:\xxx\Marlin\src\HAL\shared\HAL.cpp

I fixed it by adding a #define in front of it.
The line reads: #define MarlinHAL hal;

Still strange is, that I get this error only on the BIGTREETECH-OCTOPUS-V1.0-master and not on the original Marlin-bugfix-2.0.x

Details: Win10 / German / PlatformIO

**Comment by gdumont2211** [comment]
hi, i don't see where i can add the #define, can u help me?
