### ISSUE TITLE
Add 128Kib bootloader for STM32H723 board

### ISSUE THREAD

**Issue by trevor-pfeil** [bigtreetech/BIGTREETECH-OCTOPUS-V1.0#138]
I am trying to reflash the bootloader for an Octopus Pro V1.0 with the STM32H723 chip. The files in this repo only contain 32Kib bootloaders for STM32F446, STM32F429, and STM32F407. There is no bootloader.hex file for the STM32H723 chip so it should be added to increase support for this processor

**Comment by Raymond3D** [comment]
Did you ever get the bootloader for the STM32H723?

Seem to have messed up my board

**Comment by trevor-pfeil** [comment]
Yeah - they added it to the bootloader folder
https://github.com/bigtreetech/BIGTREETECH-OCTOPUS-V1.0/tree/master/Firmware/DFU%20Update%20bootloader/bootloader
