### ISSUE TITLE
Driver drv8825 plugged in the wrong way, board defective?

### ISSUE THREAD

**Issue by Skippydi** [bigtreetech/BIGTREETECH-OCTOPUS-V1.0#165]
I accidentally plugged the drv8825 driver into my Octopus V1.1 board the wrong way round. Now the board is neither recognized via USB nor can I flash it. What could be wrong? Shouldn't the board be able to withstand something like that?

**Comment by Daneild** [comment]
I have the same board, there are some fuses on it, check them.  Also, try and use the jumper to be powered on from usb and do not connect the power to it. Hope it will help..somehow.

**Comment by Skippydi** [comment]
Hi Daneild, i have all Fußes checked, all are OK . Jumper on powered in USB has No effect.I don't know why such a small problem can cause such a serious error. Even a request to BTT was ignored. For me, BTT has extremely bad hardwareVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Daneild ***@***.***> Datum: 07.05.24  23:35  (GMT+03:00) An: "bigtreetech/BIGTREETECH-OCTOPUS-V1.0" ***@***.***> Cc: Skippydi ***@***.***>, Author ***@***.***> Betreff: Re: [bigtreetech/BIGTREETECH-OCTOPUS-V1.0] Driver drv8825 plugged in the wrong way, board defective? (Issue #165) 
I have the same board, there are some fuses on it, check them.  Also, try and use the jumper to be powered on from usb and do not connect the power to it. Hope it will help..somehow.

**Comment by looxonline** [comment]
> Hi Daneild, i have all Fußes checked, all are OK . Jumper on powered in USB has No effect.I don't know why such a small problem can cause such a serious error. Even a request to BTT was ignored. For me, BTT has extremely bad hardwareVon meinem/meiner Galaxy gesendet -------- Ursprüngliche Nachricht --------Von: Daneild ***@***.***> Datum: 07.05.24 23:35 (GMT+03:00) An: "bigtreetech/BIGTREETECH-OCTOPUS-V1.0" ***@***.***> Cc: Skippydi ***@***.***>, Author ***@***.***> Betreff: Re: [bigtreetech/BIGTREETECH-OCTOPUS-V1.0] Driver drv8825 plugged in the wrong way, board defective? (Issue #165) I have the same board, there are some fuses on it, check them. Also, try and use the jumper to be powered on from usb and do not connect the power to it. Hope it will help..somehow. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Unfortunately this sort of error connection is difficult to protect against and does indeed cause damage to the motherboard. We included protection against in in earlier motherboards but it unfortunately can cause other issues due to increased resistance in the ground path. Our solution was to introduce the EZ range of drivers which completely prevent incorrectly inserting the drivers by keying them. You will struggle to find any motherboard on the market that uses stepstick drivers and can effectively protect against reverse insertion.
