### ISSUE TITLE
Octopus not detected

### ISSUE THREAD

**Issue by sims-60** [bigtreetech/BIGTREETECH-OCTOPUS-V1.0#22]
I connected the octopus to my pc and then on the octopus the leds also light up but the pc don't detect the octopus board

**Comment by dazkit** [comment]
try that https://github.com/bigtreetech/BIGTREETECH-OCTOPUS-V1.0/issues/17

**Comment by sims-60** [comment]
ok

**Comment by dazkit** [comment]
![grafik](https://user-images.githubusercontent.com/45803283/121208864-ada88580-c87a-11eb-9342-172b3f7197d0.png)
you have to put this jumper to connect via usb

**Comment by sims-60** [comment]
but when it is the sd card reader why the pc then can't connect to the board

**Comment by dazkit** [comment]
do you use an external power supply or do you only connect it with usb? If you only connect it with USB you have to set the jumper next to the Power LED

**Comment by sims-60** [comment]
i use usb and i have set the jumper and the leds also light up

**Comment by dazkit** [comment]
Try to set the Jumper at Boot0. Did  you get a USB connection?

**Comment by sims-60** [comment]
yes

**Comment by dazkit** [comment]
I had the same Problem after i installed the firmware.bin then i get a connection. Its not a Problem from the SD Card reader. Try to reinstall the firmware.bin

**Comment by sims-60** [comment]
what do you mean with reinstall the firmware.bin

**Comment by dazkit** [comment]
Firmware is marlin or klipper. Which one do you want to use?

**Comment by sims-60** [comment]
klipper

**Comment by dazkit** [comment]
https://github.com/bigtreetech/BIGTREETECH-OCTOPUS-V1.0/blob/main/BIGTREETECH_Octopus_EN.pdf

here on page 20. You have to create a firmware.bin and insert it into the board with a MicroSD card and transfer it

**Comment by sims-60** [comment]
i know

**Comment by sims-60** [comment]
have you discord? because i cant send my firmware on github github not support .bin files

**Comment by dazkit** [comment]
sorry i have no discord. I had the same Problem after i create the firmware.bin and transfer it with a sd card my board was not recognized with USB. Than i used a different SD Card and now it works. I think you have the Same Problem as me. If that's not the problem, then your board is probably broken

**Comment by sims-60** [comment]
do you use klipper?

**Comment by sims-60** [comment]
and  i have the exat same problem

**Comment by sims-60** [comment]
can you send me your firmware.bin?

**Comment by sims-60** [comment]
here is my email

**Comment by sims-60** [comment]
fkp00065@zwoho.com
its a trash mail which only exist for 10 minutes

**Comment by dazkit** [comment]
okay

**Comment by sims-60** [comment]
thank you

**Comment by sims-60** [comment]
I WORKS

**Comment by sims-60** [comment]
i think i had an error im my firmware

**Comment by dazkit** [comment]
Ok then close this thread and have fun :)

**Comment by sims-60** [comment]
thank you

**Comment by lowtolerance** [comment]
Can I have this magic firmware.bin? I can't seem to get this board to recognize my binary off of the SD card, and IDK if it's the binary of the board. A known-good klipper binary would be a big help, and I'm not sure why BTT doesn't give publish one themselves.

**Comment by sims-60** [comment]
hi  can you send a mail to this mail : sqf86920@eoopy.com?
then i will send you the firmware

**Comment by sims-60** [comment]
because i can't send a .bin file with github

**Comment by lowtolerance** [comment]
I actually managed to sort this out myself, I don't think your firmware
would have helped. I jumped two of the wrong pins for sensorless homing and
I think it was putting the bootloader into an error state.

**Comment by sims-60** [comment]
oh ok in this moment i wanted to send you the email XDDDD

**Comment by Voodoobrew101** [comment]
I dont use klipper, but in Marlin these sound like the types of issues you get when you use the wrong 
#define SERIAL_PORT           1  // TFT
#define SERIAL_PORT_2      -1  // USB
#define SERIAL_PORT_3       2  // RPI, Raspberry Pi
settings. In my experience the order is also important. My settings are as above, which are the defaults in this github.

**Comment by drelich** [comment]
I know this is a year old topic, and I hate to resurrect it, but just was dealing with the same thing. For two hours I was pulling my hair because I couldn't see any response to either `lsusb` nor `ls /dev/serial/by-id/*`

Turned out I accidentally compiled Klipper FW with the wrong MCU frequency. My board is model 429 with MCU freq. of 8MHz but I compiled the FW for the other version with 12MHz. Once I realised my mistake and recompiled FW with the correct frequency, the board indeed came back to life and I could see meaningful output to both the `lsusb` and `ls /dev/serial/by-id/*` commands.

Just thought I'd share in case somebody made the same mistake :)

**Comment by whatder1** [comment]
> I know this is a year old topic, and I hate to resurrect it, but just was dealing with the same thing. For two hours I was pulling my hair because I couldn't see any response to either `lsusb` nor `ls /dev/serial/by-id/*`
> 
> Turned out I accidentally compiled Klipper FW with the wrong MCU frequency. My board is model 429 with MCU freq. of 8MHz but I compiled the FW for the other version with 12MHz. Once I realised my mistake and recompiled FW with the correct frequency, the board indeed came back to life and I could see meaningful output to both the `lsusb` and `ls /dev/serial/by-id/*` commands.
> 
> Just thought I'd share in case somebody made the same mistake :)

How did you get the updated firmware installed?  Using the SD?  I ask because I think I may have bricked mine but I can't seem to update the firmware using the SD card (downloaded a stock firmware file from BTT's GitHub, renamed it to firmware.bin and inserted into the Octopus).  the firmware file hasn't been renamed so I suspect that it isn't flashing...
