### ISSUE TITLE
Connecting Raspberry Pi 4B directly to Octopus v1.1 J26 pins

### ISSUE THREAD

**Issue by amv101** [bigtreetech/BIGTREETECH-OCTOPUS-V1.0#68]
I want to connect the Raspberry Pi to the Octopus board via USB for the data, but I wanted to use the 5V output pins (J26) on the Octopus board to run power to the Pi.

My question is, can the Octopus board handle the needed 2.5A current to run the Pi? There are two 5V outputs on the J26 connecter, and 6 grounds. Both 5V seem to be on the same trace, so could I just connect to a single 5V pin and one to the ground? I dont want to run data through the J26, just use the power.

There really isnt much info on connecting the Pi to these connections. Maybe someone has a writeup somewhere?

**Comment by peter-neu** [comment]
From the documentation the board can handle this: 12V (4A), 5V (8A) and 3.3V (1A)
So yes, you can connect the raspberry there, just connect it, when the diameter of your cable is too small you need to connect two wires.
