### ISSUE TITLE
Had to double rotation distance. Is this safe?

### ISSUE THREAD

**Issue by FlatEarthDave** [bigtreetech/BIGTREETECH-OCTOPUS-V1.0#81]
For whatever reason, I can't figure out, I have to double all of my stepper motor rotation distances for X, Y, Z, and E0 in Klipper from the values that worked just before changing my board to a BTT Octopus V1.1, and are in the config file provided on Github, ie X,Y from 40 to 80, Z from 8 to 16, and E0 from 22.857 to 45.714. I made zero changes other than the board. For proof, here is the section from my config that is working perfectly:

`[stepper_x]
step_pin: PG0
dir_pin: !PG1
enable_pin: !PF15
microsteps: 16
rotation_distance: 80
endstop_pin: PG6
position_endstop: 260
position_max: 260
homing_speed: 50

[stepper_y]
step_pin: PF13
dir_pin: PF12
enable_pin: !PF14
microsteps: 16
rotation_distance: 80
endstop_pin: PG9
position_endstop: 260
position_max: 260
homing_speed: 50

[stepper_z]
step_pin: PF11
dir_pin: !PG3
enable_pin: !PG5
microsteps: 16
rotation_distance: 16
endstop_pin: PG10
position_endstop: 0.5
position_max: 400`

I don't really like that I have to remember to double those values, but I guess I can live with it, as long as it's safe to continue using this way. Is there something wrong with the drivers?

**Comment by c3charvat** [comment]
It sounds like your jumpers on the octopus are set to a different mirco stepping value then you are specifying. Try 2* your Mirostepping and and retuning your code back to the old set up. See if that works ..

**Comment by FlatEarthDave** [comment]
Still not sure what happened, but I changed the voltage on one fan to 12v from 24v, and the board popped and smoked. Bought another board and configured the same as the previous one, I reverted all values back to their originals and now it works. Just wish I would've bought the pro with the integrated chip for a PT100.

Thanks for your help,

Dave

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
